name: aivideo

services:
  app:
    image: ${COMPOSE_PROJECT_NAME}-dev:latest
    command: ["sh", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 7001 --reload"]
    networks:
      - hng-network
    restart: unless-stopped
    ports:
      - 7100:7001
    working_dir: /app 
    volumes:
      - .env:/app/.env    
    depends_on:
      db:
        condition: service_healthy
        

  db:
    image: postgres:14.12
    restart: always
    volumes:
      - ${COMPOSE_PROJECT_NAME}_db:/var/lib/postgresql/data
      - .env:/app/.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_DB=${DB_NAME?Variable not set}
    networks:
      - hng-network
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:

networks:
  hng-network:
    driver: bridge