services:
  aivideo_app_prod:
    image: aivideo-prod:latest
    ports:
      - 7103:7001  
    depends_on:
      aivideo_prod_db
        condition: service_healthy

  aivideo_prod_db:
    volumes:
      - aivideo_prod_db:/var/lib/postgresql/data
      - .env:/app/.env
    healthcheck:
      test: pg_isready -U pythonteam -d python_prod_db
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  aivideo_prod_db:

