"""update project

Revision ID: 1c757ccfd13f
Revises: 88fc821b35d2
Create Date: 2024-08-13 10:28:28.247502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "1c757ccfd13f"
down_revision: Union[str, None] = "88fc821b35d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    project_status = postgresql.ENUM(
        "rejected", "failed", "pending", "completed", name="projectstatus"
    )
    project_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("duration", sa.String(), nullable=True))
    op.add_column("projects", sa.Column("size", sa.String(), nullable=False))
    op.add_column(
        "projects",
        sa.Column(
            "status",
            sa.Enum("rejected", "failed", "pending", "completed", name="projectstatus"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "status")
    op.drop_column("projects", "size")
    op.drop_column("projects", "duration")
    # ### end Alembic commands ###
