"""update job and project model

Revision ID: 34325fd8c1e1
Revises: e3849c994412
Create Date: 2024-08-14 14:38:21.997904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34325fd8c1e1'
down_revision: Union[str, None] = 'e3849c994412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_active')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###
