"""added text_to_videos table, text_to_videos.user, and users.text_to_videos

Revision ID: 61b3a115b6c2
Revises: c4e93820aeaf
Create Date: 2024-08-16 02:51:18.329781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b3a115b6c2'
down_revision: Union[str, None] = 'c4e93820aeaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_to_vdeos',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='Task is in queue', nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('gif_url', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_to_vdeos_id'), 'text_to_vdeos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_to_vdeos_id'), table_name='text_to_vdeos')
    op.drop_table('text_to_vdeos')
    # ### end Alembic commands ###
