"""update testimonial model

Revision ID: 764d60fda655
Revises: 2afb0259557d
Create Date: 2024-08-15 11:38:22.208686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764d60fda655'
down_revision: Union[str, None] = '2afb0259557d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('client_position', sa.String(), nullable=False))
    op.add_column('testimonials', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'avatar_url')
    op.drop_column('testimonials', 'client_position')
    # ### end Alembic commands ###
