"""update projects table

Revision ID: 88fc821b35d2
Revises: 384db91fec7b
Create Date: 2024-08-13 06:16:26.075233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88fc821b35d2'
down_revision: Union[str, None] = '384db91fec7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('result', sa.String(), nullable=True))
    op.alter_column('projects', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('projects', 'result')
    # ### end Alembic commands ###
