"""initial migration

Revision ID: 961bc4c07299
Revises: 67a7708dda66
Create Date: 2024-08-15 19:04:51.003466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961bc4c07299'
down_revision: Union[str, None] = '67a7708dda66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('background_music', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('testimonials', sa.Column('client_position', sa.String(), nullable=False))
    op.add_column('testimonials', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'avatar_url')
    op.drop_column('testimonials', 'client_position')
    op.drop_column('background_music', 'file_path')
    op.drop_column('avatars', 'file_path')
    # ### end Alembic commands ###
