"""message

Revision ID: a2aee69efd58
Revises: 66c35250c05b
Create Date: 2024-08-15 17:35:31.317720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2aee69efd58'
down_revision: Union[str, None] = '66c35250c05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not op.get_bind().dialect.has_table(op.get_bind(), "avatars"):
        op.create_table(
            'avatars',
            sa.Column('file_url', sa.String(), nullable=False),
            sa.Column('file_name', sa.String(), nullable=True),
            sa.Column('file_path', sa.String(), nullable=True),
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.PrimaryKeyConstraint('id')
            )
        op.create_index(op.f('ix_avatars_id'), 'avatars', ['id'], unique=False)
        op.create_table('background_music',
            sa.Column('file_url', sa.String(), nullable=False),
            sa.Column('file_name', sa.String(), nullable=True),
            sa.Column('file_path', sa.String(), nullable=True),
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.PrimaryKeyConstraint('id')
            )
        op.create_index(op.f('ix_background_music_id'), 'background_music', ['id'], unique=False)
        op.drop_index('ix_job_applications_id', table_name='job_applications')
        op.drop_table('job_applications')
        op.drop_index('ix_celery_tasks_id', table_name='celery_tasks')
        op.drop_table('celery_tasks')
        op.add_column('jobs', sa.Column('job_id', sa.String(), nullable=False))
        op.add_column('jobs', sa.Column('project_id', sa.String(), nullable=True))
        op.add_column('jobs', sa.Column('user_id', sa.String(), nullable=True))
        op.add_column('jobs', sa.Column('status', sa.String(), server_default='PENDING', nullable=True))
        op.add_column('jobs', sa.Column('result', sa.Text(), nullable=True))
        op.create_foreign_key(None, 'jobs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        op.drop_column('jobs', 'is_deleted')
        op.drop_column('jobs', 'title')
        op.drop_column('jobs', 'job_type')
        op.drop_column('jobs', 'department')
        op.drop_column('jobs', 'description')
        op.drop_column('jobs', 'location')
        op.drop_column('jobs', 'company_name')
        op.drop_column('jobs', 'salary')
        op.add_column('projects', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
        op.alter_column(
            'projects', 'result',
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            existing_nullable=True)
        op.add_column('testimonials', sa.Column('client_position', sa.String(), nullable=False))
        op.add_column('testimonials', sa.Column('avatar_url', sa.String(), nullable=True))
        op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
            # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('testimonials', 'avatar_url')
    op.drop_column('testimonials', 'client_position')
    op.alter_column(
        'projects', 'result',
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True)
    op.drop_column('projects', 'is_active')
    op.add_column('jobs', sa.Column('salary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'result')
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'user_id')
    op.drop_column('jobs', 'project_id')
    op.drop_column('jobs', 'job_id')
    op.create_table('celery_tasks',
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='celery_tasks_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='celery_tasks_pkey')
    )
    op.create_index('ix_celery_tasks_id', 'celery_tasks', ['id'], unique=False)
    op.create_table('job_applications',
    sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('applicant_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('applicant_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cover_letter', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resume_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('portfolio_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('application_status', postgresql.ENUM('pending', 'accepted', 'rejected', name='application_status'), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='job_applications_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='job_applications_pkey')
    )
    op.create_index('ix_job_applications_id', 'job_applications', ['id'], unique=False)
    op.drop_index(op.f('ix_background_music_id'), table_name='background_music')
    op.drop_table('background_music')
    op.drop_index(op.f('ix_avatars_id'), table_name='avatars')
    op.drop_table('avatars')
    # ### end Alembic commands ###
