"""add is_published to resources table

Revision ID: c4e93820aeaf
Revises: 691c482d5eff
Create Date: 2024-08-15 22:21:43.539615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e93820aeaf'
down_revision: Union[str, None] = '691c482d5eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'is_published')
    # ### end Alembic commands ###
