"""rename celery tasks to job table

Revision ID: e3849c994412
Revises: 3f2863810ea4
Create Date: 2024-08-13 17:11:12.306502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3849c994412'
down_revision: Union[str, None] = '3f2863810ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_applications_id', table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index('ix_celery_tasks_id', table_name='celery_tasks')
    op.drop_table('celery_tasks')
    op.add_column('jobs', sa.Column('job_id', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('project_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('status', sa.String(), server_default='PENDING', nullable=True))
    op.add_column('jobs', sa.Column('result', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('jobs', 'title')
    op.drop_column('jobs', 'salary')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'job_type')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'is_deleted')
    op.drop_column('jobs', 'company_name')
    op.drop_column('jobs', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('salary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'result')
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'project_id')
    op.drop_column('jobs', 'job_id')
    op.create_table('celery_tasks',
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='celery_tasks_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='celery_tasks_pkey')
    )
    op.create_index('ix_celery_tasks_id', 'celery_tasks', ['id'], unique=False)
    op.create_table('job_applications',
    sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('applicant_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('applicant_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cover_letter', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resume_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('portfolio_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('application_status', postgresql.ENUM('pending', 'accepted', 'rejected', name='application_status'), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='job_applications_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='job_applications_pkey')
    )
    op.create_index('ix_job_applications_id', 'job_applications', ['id'], unique=False)
    # ### end Alembic commands ###
