"""update avatar and background music table

Revision ID: f35492571c7a
Revises: 34325fd8c1e1
Create Date: 2024-08-15 12:02:24.507597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35492571c7a'
down_revision: Union[str, None] = '34325fd8c1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if 'file_path' column exists in 'avatars' table
    columns = [col['name'] for col in inspector.get_columns('avatars')]
    if 'file_path' not in columns:
        
        op.add_column('avatars', sa.Column('file_path', sa.String(), nullable=True))
        op.add_column('background_music', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('avatars')]
    if 'file_path' in columns:
        op.drop_column('background_music', 'file_path')
        op.drop_column('avatars', 'file_path')
    # ### end Alembic commands ###
