name: Dev Deployment

on:
  # push:
  #   branches: [dev]
  #   paths-ignore:
  #     - "README.md"
  #     - ".github/workflows/**"
  #     - ".gitignore"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: pydeploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd aivideo_be/dev
            git add .
            git stash
            git pull origin dev
            source venv/bin/activate
            pip install -r requirements.txt
            alembic version --autogenerate
            alembic upgrade head
