name: Dev cd pipeline
on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t aivideo-dev:latest -f Dockerfile .

      - name: Save image 
        run: docker save aivideo-dev:latest | gzip > aivideo-dev.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "aivideo-dev.tar.gz"
          target: "/home/${{ secrets.USERNAME }}/aivideo_be/dev"
 
      - name: Deploy image on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/${{ secrets.USERNAME }}/aivideo_be/dev
            git pull origin dev
            gunzip -c aivideo-dev.tar.gz | docker load
            docker compose up -d
            rm -f aivideo-dev.tar.gz
