name: Prod cd pipeline
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t aivideo-prod:latest -f Dockerfile .

      - name: Save image 
        run: docker save aivideo-prod:latest | gzip > aivideo-prod.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "aivideo-prod.tar.gz"
          target: "/home/${{ secrets.USERNAME }}/aivideo_be/prod"
 
      - name: Deploy image on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/${{ secrets.USERNAME }}/aivideo_be/prod
            git pull origin main
            docker load --input aivideo-prod.tar.gz
            docker compose -f compose.yml -f compose.prod.yml up -d
            rm -f aivideo-prod.tar.gz
