name: Production Deployment

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: hng-runner
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd aivideo_be/prod
            git add .
            git stash
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt --no-deps --use-deprecated=legacy-resolver
            alembic revision --autogenerate
            alembic upgrade head
            pm2 restart aivideo_be_prod --update-env
            pm2 restart jobs_script_prod

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: deploy
    permissions:
      contents: write
      issues: write 
      pull-requests: write 
      id-token: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "latest"
          
      - name: Install depedencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Install semantic-release and plugins
        run: pnpm add semantic-release @semantic-release/git @semantic-release/github --save-dev
        
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx semantic-release
