name: Prod Branch Deployment

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  on-success:
    runs-on: pydeploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd aivideo-python-be/prod/
            git pull origin main
            source .venv/bin/activate
            pip install -r requirements.txt
            alembic upgrade head
