name: Staging Deployment

on:
  push:
    branches: [staging]
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: aivid
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Main Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd aivideo_be/staging
            git add .
            git stash
            git pull origin staging
            source venv/bin/activate
            pip install -r requirements.txt --no-deps --use-deprecated=legacy-resolver
            alembic revision --autogenerate
            alembic upgrade head
        
      - name: Deploy to Worker Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WORKER_HOST }}
          username: ${{ secrets.WORKER_USERNAME }}
          password: ${{ secrets.WORKER_PASSWORD }}
          script: |
            cd aivideo_be/staging
            git add .
            git stash
            git pull origin staging
            source venv/bin/activate
            pip install -r requirements.txt --no-deps --use-deprecated=legacy-resolver
            pm2 reload aivideo_celery_staging
