name: Staging Branch Deployment

on:
  push:
    branches: [staging]
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  on-success:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd aivideo-python-be/staging/
            git pull origin staging
            source .venv/bin/activate
            pip install -r requirements.txt
            alembic upgrade head
